Add RoPE with FlexBert blocks
AnswerDotAI/bert24 pull request #36
Opened 2024-05-26 13:23 UTC by staghado

This implements RoPE for BERT. See #3

It uses the rotary embedding kernel from [flash_attn](https://github.com/Dao-AILab/flash-attention/blob/main/flash_attn/layers/rotary.py). In the unpadded version, we first have to pad -> rope -> unpad, this is cheap especially for the model sizes we are considering.

The unpadded rope version still achieves better throughput than the padded one at large sequence lengths even with the pad/unpad logic which means that the rotary operation is negligible compared to the attention.
![compare-seqlen-rope](https://github.com/AnswerDotAI/bert24/assets/84044788/ed0870d4-2303-42ee-826d-7aebec5cff33)

2024-05-27 01:02 UTC, ohallstrom requested changes
Looks good in general to me, but please look at the comments I have made and make the corresponding fixes.

Would appreciate if we could have another set of eyes on this PR as well, might missed something as its late..:)

2024-05-27 01:09 UTC, ohallstrom commented
Also, a question to the other reviewers: Would we want to support of RoPE based on position IDs?

2024-05-27 01:14 UTC, ohallstrom commented
Also, it seems like @staghado has incorporated some code from #35 , we should make sure these changes align fully with #35 once it has been merged

2024-05-27 07:49 UTC, iacolippo commented on src/bert_layers/attention.py
> +            config.rotary_emb_dim,
It depends if we want to enable partial rotary like in GPT-J. Not sure about it

2024-05-27 07:51 UTC, staghado commented on src/bert_layers/attention.py
> +            qkv = qkv.view(unpad_bs, -1, 3, self.num_attention_heads, self.attn_head_size)
yeah it's left from debugging

2024-05-27 07:58 UTC, staghado commented on src/bert_layers/embeddings.py
> +    def forward(self, input_ids: torch.LongTensor, position_ids: Optional[torch.LongTensor] = None) -> torch.Tensor:
It's not used but is added in order to have an identical interface between **SansPositionEmbeddings**  and **AbsoluteEmbeddings**. Avoids having custom logic in the model forward.

2024-05-27 08:01 UTC, staghado commented on yamls/main/flex-bert-base.yaml
I think it should as there is an inconsistent use of lower and uppercase for true/false. For train_small i'll remove it but it shouldn't be an issue as we will have our custom data splits.

2024-05-27 08:06 UTC, ohallstrom commented on src/bert_layers/attention.py
> +            config.rotary_emb_dim,
If we want to enable partial rotary a solution is then simply just to set rotary_embed_size to None as default in https://github.com/AnswerDotAI/bert24/pull/36#discussion_r1615374459 . If None, then the embed dim should be set to attn_head_size. Else we can override it when we want to do partial rotary. That way we don't have to change the config twice if not doing partial rotary.

2024-05-27 08:26 UTC, ohallstrom commented on yamls/main/flex-bert-base.yaml
In that case one could argue that it should be in a different PR as it has nothing to do with RoPE. But for me it is ok

2024-05-27 19:42 UTC, ohallstrom commented on src/bert_layers/attention.py
> +        attn = attn.contiguous().view(batch_size, seqlen, dim)
missing a transpose(1, 2) here? attn has shape (bs, n_heads, seq_len, head_dim)

2024-05-27 19:43 UTC, ohallstrom commented on src/bert_layers/attention.py
> +            attn = attn.transpose(1, 2).view(unpad_bs, -1, dim)
double transpose(1, 2), one should be removed 😅

2024-05-28 11:16 UTC, ohallstrom reviewed
LGTM overall, just address the two comments and I believe we can merge

2024-05-28 11:16 UTC, ohallstrom commented on src/bert_layers/attention.py
> +        attn = attn.contiguous().view(batch_size, seqlen, dim)
Itranspose(1,2) missingno?

2024-05-28 11:16 UTC, ohallstrom commented on src/bert_layers/attention.py
> +            qkv = qkv.view(batch_size, seqlen, 3, self.num_attention_heads, self.attn_head_size)
This row (and 611) could be moved out of the if and else statement as both if and else start with the same row

2024-05-28 13:29 UTC, merged